### DISCUSSION TITLE
Dragging work on the responsive preview but doesn't in the desktop view

### DISCUSSION THREAD

**Discussion by GuillaumeTech** [pmndrs/use-gesture#341] [Q&A] [answered]
Hi !

First off, thanks for your work on this lib. I'm messing around a bit with it to create a simple image pan/zoom component
It's working like charm on the mobile preview in Chrome. However when I switch to the usual desktop view I can only pan for a tiny amount then my cursor is disabled.

Here is a video of it, what you see in the console is the offset values :
https://user-images.githubusercontent.com/27060431/127081364-279fff8b-3663-4091-b69f-6ac948c0f761.mp4

I'm without a doubt missing something but I can't figure out what, did anyone encountered the same issue ? or have and idea ?
I've tried allowing all pointer-event on the image so I could  get rid of that `not-allowed` cursor but it didn't do anything

I'm using Chrome 91.0.4472.164 
here is my code, I started from `npx create-react-app my-app --template typescript`, so adding `Pan.tsx` and updating` App.tsx `and `Index.css` should get you the same setup

Pan.tsx
```tsx
import React, {useState, useRef} from 'react';

import {useDrag} from '@use-gesture/react'
type Props = {
  imageSrc: string;
}; 


function ImagePanner( { imageSrc }: Props) {
  let imageRef = useRef(null)
  const [offset, setOffset] = useState({x:0,y:0})
  useDrag(({offset: [dx,dy]} :{offset:Array<number>})=>{
    setOffset({x:dx, y:dy})
    console.log(dx,dy)
  }, { target: imageRef }

  )
  const {x, y} = offset
  return (
    <>
    <div className="pan-container">
     <img src={imageSrc} 
      ref={imageRef}
      style={{
        transform: `translate(${x}px, ${y}px)`
      }}
      className="image-pan" />
    </div>
    </>
  );
}

export default ImagePanner;
```

Index.css
```css
.pan-container{
  overflow: hidden;
  width: 70rem;
  height: 70rem;
  margin: auto;
  pointer-events: all;
  touch-action: none;
}

.image-pan{
  position: relative;
  touch-action: none;
  pointer-events: all;
  cursor: pointer;
}
```

App.tsx
```tsx
import './App.css';
import ImagePanner from './Pan';
import image from './image-test.jpg'

function App() {
  return (
    <div className="App">
      <ImagePanner imageSrc={image} />
    </div>
  );
}

export default App;
```
